# Generated by Django 2.1 on 2018-08-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emial',
            new_name='email',
        ),
    ]
